- name: Get PVE_NODE_NAME
  command: echo $PVE_NODE_NAME
  register: pve_node_name

- name: Get PVE_NODE_TYPE
  command: echo $PVE_NODE_TYPE
  register: pve_node_type

- name: "Make Directory /etch/rancher/rke2"
  file:
    path: /etc/rancher/rke2
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "Generate RKE2 config"
  template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    mode: 755
    force: yes
  when: inventory_hostname in groups['controller']
  vars:
    node_name: "{{ pve_node_name.stdout }}"
    node_type: "{{ pve_node_type.stdout }}"
- name: "Generate RKE2 Agent config"
  template:
    src: config-agent.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: 755
    force: yes
  when: inventory_hostname in groups['worker']
  vars:
    node_name: "{{ pve_node_name.stdout }}"
    node_type: "{{ pve_node_type.stdout }}"
