- name: "Make Directory /etch/rancher/rke2"
  file: 
    path: /etc/rancher/rke2
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "Generate RKE2 config"
  template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: 0644
    force: yes
  when: inventory_hostname in groups['controller']
- name: "Generate RKE2 Agent config"
  template:
    src: config-agent.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: 0644
    force: yes
  when: inventory_hostname in groups['worker']