- name: "install rke2"
  shell: |
    curl -sfL https://get.rke2.io | sh -
  when: inventory_hostname in groups['controller']
  environment:
    INSTALL_RKE2_VERSION: "{{ rke2_version }}"
- name: "install rke2 Agent"
  shell: |
    curl -sfL https://get.rke2.io | sh -s -- agent
  when: inventory_hostname in groups['worker']
  environment:
    INSTALL_RKE2_VERSION: "{{ rke2_version }}"
