- name: "Update Packages"
  apt:
    update_cache: yes
- name: "Check internet connectivity"
  uri:
    url: "http://www.google.com"
    status_code: 200
- name: "add hostnames of controllers to /etc/hosts"
  blockinfile:
    state: present
    dest: /etc/hosts
    content: |
      {% for host in groups.cluster %}
      {{ hostvars[host].ansible_host }} {{ hostvars[host].inventory_hostname }}
      {% endfor %}
- name: "add hostnames of controllers to /etc/cloud/templates/hosts.debian.tmpl when using cloud-init"
  blockinfile:
    state: present
    dest: /etc/cloud/templates/hosts.debian.tmpl
    content: |
      {% for host in groups.cluster %}
      {{ hostvars[host].ansible_host }} {{ hostvars[host].inventory_hostname }}
      {% endfor %}
- name: "Install open-iscsi"
  apt:
    name: open-iscsi
    state: present
- name: "Install nfs-common"
  apt:
    name: nfs-common
    state: present
# cryptsetup
- name: "Install cryptsetup"
  apt:
    name: cryptsetup
    state: present

# dmsetup
- name: "Install dmsetup"
  apt:
    name: dmsetup
    state: present
